import { prisma } from './prisma';
import { TicketStatus, TicketCategory } from './generated/prisma/client';

const tickets = [
	// TECHNICAL – OPEN
	{
		subject: 'Video player freezes on lesson 4 of the JavaScript course',
		body: "Hi, the video player keeps freezing at around the 8-minute mark on lesson 4. I've tried refreshing and clearing cache but the issue persists. Using Chrome 124 on Windows 11.",
		fromEmail: 'james.harris@gmail.com',
		fromName: 'James Harris',
		status: TicketStatus.OPEN,
		category: TicketCategory.TECHNICAL,
		createdAt: new Date('2026-05-01T08:12:00Z'),
	},
	{
		subject: 'Cannot download course materials – 403 error',
		body: "Every time I click 'Download Resources' on any lesson, I get a 403 Forbidden error. My subscription is active. Please help.",
		fromEmail: 'sofia.m@outlook.com',
		fromName: 'Sofia Marchetti',
		status: TicketStatus.OPEN,
		category: TicketCategory.TECHNICAL,
		createdAt: new Date('2026-05-02T09:45:00Z'),
	},
	{
		subject: 'Course progress not saving between sessions',
		body: 'I finished the first 3 modules yesterday but today all my progress was reset to zero. This has happened twice now.',
		fromEmail: 'liam.o.brien@yahoo.com',
		fromName: "Liam O'Brien",
		status: TicketStatus.OPEN,
		category: TicketCategory.TECHNICAL,
		createdAt: new Date('2026-05-03T11:00:00Z'),
	},
	{
		subject: 'Two-factor authentication codes not arriving via SMS',
		body: "I enabled 2FA last week and now I can't log in because the SMS codes never arrive. I've checked my phone is working fine.",
		fromEmail: 'aisha.nkosi@gmail.com',
		fromName: 'Aisha Nkosi',
		status: TicketStatus.OPEN,
		category: TicketCategory.TECHNICAL,
		createdAt: new Date('2026-05-04T07:30:00Z'),
	},
	{
		subject: 'Code playground throws syntax errors on valid JavaScript',
		body: "The in-browser code editor keeps highlighting correct arrow functions as syntax errors. Const declarations with let inside loops also seem broken.",
		fromEmail: 'chen.wei.dev@hotmail.com',
		fromName: 'Chen Wei',
		status: TicketStatus.OPEN,
		category: TicketCategory.TECHNICAL,
		createdAt: new Date('2026-05-05T14:20:00Z'),
	},
	{
		subject: 'Mobile app crashes on iPad when switching between modules',
		body: 'The iOS app crashes every time I tap to switch to a different module. Running iPadOS 17.4 on an iPad Air 5th gen.',
		fromEmail: 'priya.sharma.tech@gmail.com',
		fromName: 'Priya Sharma',
		status: TicketStatus.OPEN,
		category: TicketCategory.TECHNICAL,
		createdAt: new Date('2026-05-06T10:05:00Z'),
	},
	{
		subject: 'Certificate not generated after completing React course',
		body: "I completed all lessons and passed the final quiz with 92% but no certificate was issued. The dashboard still shows 'certificate pending'.",
		fromEmail: 'marco.bianchi@libero.it',
		fromName: 'Marco Bianchi',
		status: TicketStatus.OPEN,
		category: TicketCategory.TECHNICAL,
		createdAt: new Date('2026-05-07T15:40:00Z'),
	},
	{
		subject: 'Subtitles out of sync on Python Fundamentals videos',
		body: 'The English subtitles are about 3–4 seconds behind the audio in the Python Fundamentals course, starting from lesson 7.',
		fromEmail: 'yuki.tanaka.learn@gmail.com',
		fromName: 'Yuki Tanaka',
		status: TicketStatus.OPEN,
		category: TicketCategory.TECHNICAL,
		createdAt: new Date('2026-05-08T08:55:00Z'),
	},
	{
		subject: 'Search results return irrelevant courses',
		body: "When I search for 'TypeScript generics' the results show beginner HTML courses. The search seems completely broken.",
		fromEmail: 'fatima.al.zahra@proton.me',
		fromName: 'Fatima Al-Zahra',
		status: TicketStatus.OPEN,
		category: TicketCategory.TECHNICAL,
		createdAt: new Date('2026-05-09T12:10:00Z'),
	},
	{
		subject: 'Dark mode settings not persisting after logout',
		body: 'I set dark mode in preferences, but every time I log back in the interface reverts to light mode.',
		fromEmail: 'ethan.brooks.code@gmail.com',
		fromName: 'Ethan Brooks',
		status: TicketStatus.OPEN,
		category: TicketCategory.TECHNICAL,
		createdAt: new Date('2026-05-10T16:30:00Z'),
	},

	// TECHNICAL – RESOLVED
	{
		subject: 'Cannot enrol in Node.js course after purchase',
		body: "I purchased the Node.js course yesterday but when I click 'Start Learning' it says I have no active enrolment.",
		fromEmail: 'anna.kowalska@wp.pl',
		fromName: 'Anna Kowalska',
		status: TicketStatus.RESOLVED,
		category: TicketCategory.TECHNICAL,
		createdAt: new Date('2026-04-01T09:00:00Z'),
	},
	{
		subject: 'Quiz answers not being accepted — submit button unresponsive',
		body: 'On the Module 5 quiz for the SQL course, clicking Submit does nothing. No error, no response.',
		fromEmail: 'oliver.schmidt@gmx.de',
		fromName: 'Oliver Schmidt',
		status: TicketStatus.RESOLVED,
		category: TicketCategory.TECHNICAL,
		createdAt: new Date('2026-04-02T11:15:00Z'),
	},
	{
		subject: 'Audio only plays through left speaker in course videos',
		body: 'All course videos only output audio through the left channel. Tested on headphones and speakers.',
		fromEmail: 'grace.okonkwo@gmail.com',
		fromName: 'Grace Okonkwo',
		status: TicketStatus.RESOLVED,
		category: TicketCategory.TECHNICAL,
		createdAt: new Date('2026-04-03T13:45:00Z'),
	},
	{
		subject: 'Password reset email never arrives',
		body: "I requested a password reset 3 times but the email never comes. Checked spam folder too.",
		fromEmail: 'rafael.santos@terra.com.br',
		fromName: 'Rafael Santos',
		status: TicketStatus.RESOLVED,
		category: TicketCategory.TECHNICAL,
		createdAt: new Date('2026-04-04T08:20:00Z'),
	},
	{
		subject: 'Lesson bookmarks disappearing randomly',
		body: 'I bookmark lessons to revisit later but they keep disappearing. Happened at least five times this week.',
		fromEmail: 'mei.lin.study@qq.com',
		fromName: 'Mei Lin',
		status: TicketStatus.RESOLVED,
		category: TicketCategory.TECHNICAL,
		createdAt: new Date('2026-04-05T10:00:00Z'),
	},

	// TECHNICAL – CLOSED
	{
		subject: 'Course thumbnail images broken on Firefox',
		body: 'All course thumbnails show as broken images on Firefox 125. Works fine on Chrome.',
		fromEmail: 'tom.fletcher@btinternet.com',
		fromName: 'Tom Fletcher',
		status: TicketStatus.CLOSED,
		category: TicketCategory.TECHNICAL,
		createdAt: new Date('2026-03-10T09:30:00Z'),
	},
	{
		subject: 'Login page throws 500 error on submit',
		body: 'Getting a 500 Internal Server Error every time I try to log in. This started this morning.',
		fromEmail: 'diana.petrov@mail.ru',
		fromName: 'Diana Petrov',
		status: TicketStatus.CLOSED,
		category: TicketCategory.TECHNICAL,
		createdAt: new Date('2026-03-11T07:45:00Z'),
	},

	// REFUND – OPEN
	{
		subject: 'Requesting refund – course content not as described',
		body: "The React Advanced course was advertised as covering React 19 but the content is entirely about React 16. I'd like a full refund.",
		fromEmail: 'isabella.russo@gmail.com',
		fromName: 'Isabella Russo',
		status: TicketStatus.OPEN,
		category: TicketCategory.REFUND,
		createdAt: new Date('2026-05-11T10:00:00Z'),
	},
	{
		subject: 'Double charged for annual subscription',
		body: "My credit card was charged twice on the same day for my annual subscription renewal. I need one of the charges refunded immediately.",
		fromEmail: 'noah.anderson@gmail.com',
		fromName: 'Noah Anderson',
		status: TicketStatus.OPEN,
		category: TicketCategory.REFUND,
		createdAt: new Date('2026-05-12T14:30:00Z'),
	},
	{
		subject: 'Refund request – purchased wrong course by mistake',
		body: "I accidentally bought the Python Basics course instead of Python Advanced. I already own Basics. Please refund so I can buy the right one.",
		fromEmail: 'chloe.martin@orange.fr',
		fromName: 'Chloé Martin',
		status: TicketStatus.OPEN,
		category: TicketCategory.REFUND,
		createdAt: new Date('2026-05-13T09:15:00Z'),
	},
	{
		subject: 'Subscription cancelled but still charged',
		body: 'I cancelled my subscription 3 weeks ago and received a cancellation confirmation email, but I was still charged this month.',
		fromEmail: 'carlos.vega@gmail.com',
		fromName: 'Carlos Vega',
		status: TicketStatus.OPEN,
		category: TicketCategory.REFUND,
		createdAt: new Date('2026-05-14T11:45:00Z'),
	},
	{
		subject: 'Refund for team seats – company cancelled training budget',
		body: 'We purchased 10 team seats last week but our training budget has been cut. We need a refund for all seats as we are within the 14-day window.',
		fromEmail: 'sarah.johnson@acmecorp.com',
		fromName: 'Sarah Johnson',
		status: TicketStatus.OPEN,
		category: TicketCategory.REFUND,
		createdAt: new Date('2026-05-15T08:00:00Z'),
	},
	{
		subject: 'Course removed from platform – want refund',
		body: "The 'Docker for Developers' course I purchased 2 months ago has been removed from the platform. I want a refund since I can no longer access the content.",
		fromEmail: 'alex.turner@hotmail.co.uk',
		fromName: 'Alex Turner',
		status: TicketStatus.OPEN,
		category: TicketCategory.REFUND,
		createdAt: new Date('2026-05-16T13:20:00Z'),
	},

	// REFUND – RESOLVED
	{
		subject: 'Charged after free trial ended unexpectedly',
		body: 'I signed up for a 7-day free trial but was charged on day 5. I never entered billing details intentionally.',
		fromEmail: 'lucia.fernandez@gmail.com',
		fromName: 'Lucía Fernández',
		status: TicketStatus.RESOLVED,
		category: TicketCategory.REFUND,
		createdAt: new Date('2026-04-10T10:30:00Z'),
	},
	{
		subject: 'Refund request – medical emergency, unable to continue course',
		body: "Due to a medical emergency I haven't been able to use the platform for 6 weeks. I'm requesting a pro-rata refund for the unused portion of my annual plan.",
		fromEmail: 'david.kim.learn@naver.com',
		fromName: 'David Kim',
		status: TicketStatus.RESOLVED,
		category: TicketCategory.REFUND,
		createdAt: new Date('2026-04-11T14:00:00Z'),
	},
	{
		subject: 'Gift subscription refund – recipient already has account',
		body: "I bought a gift subscription for my nephew but he already has a paid account. Can I get a refund or credit?",
		fromEmail: 'margaret.walsh@eircom.net',
		fromName: 'Margaret Walsh',
		status: TicketStatus.RESOLVED,
		category: TicketCategory.REFUND,
		createdAt: new Date('2026-04-12T09:45:00Z'),
	},

	// REFUND – CLOSED
	{
		subject: 'Refund for annual plan – switching to competitor',
		body: 'I would like a refund for the remaining months of my annual plan. I have decided to use a different learning platform.',
		fromEmail: 'finn.larsen@gmail.com',
		fromName: 'Finn Larsen',
		status: TicketStatus.CLOSED,
		category: TicketCategory.REFUND,
		createdAt: new Date('2026-03-20T10:00:00Z'),
	},
	{
		subject: 'Accidental purchase on child account',
		body: 'My 10-year-old accidentally purchased a course on my account. I would like a full refund.',
		fromEmail: 'hannah.mueller@web.de',
		fromName: 'Hannah Müller',
		status: TicketStatus.CLOSED,
		category: TicketCategory.REFUND,
		createdAt: new Date('2026-03-21T15:30:00Z'),
	},

	// GENERAL – OPEN
	{
		subject: 'Question about the learning path for backend development',
		body: "I'm new to programming and want to become a backend developer. Which courses should I take and in what order?",
		fromEmail: 'amit.patel.newdev@gmail.com',
		fromName: 'Amit Patel',
		status: TicketStatus.OPEN,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-05-17T09:00:00Z'),
	},
	{
		subject: 'Can I share my account with a colleague?',
		body: 'My colleague and I work at the same company and would like to share a single account to save costs. Is this allowed under your terms?',
		fromEmail: 'tanya.ivanova@rambler.ru',
		fromName: 'Tanya Ivanova',
		status: TicketStatus.OPEN,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-05-18T11:30:00Z'),
	},
	{
		subject: 'Do you offer student discounts?',
		body: "I'm a full-time university student studying computer science. Do you have any discounted plans for students?",
		fromEmail: 'jake.morrison.student@edu.au',
		fromName: 'Jake Morrison',
		status: TicketStatus.OPEN,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-05-18T13:00:00Z'),
	},
	{
		subject: 'Requesting an invoice for company reimbursement',
		body: "I purchased the annual plan and need a formal tax invoice to submit for company reimbursement. The receipt in my account doesn't show the required GST breakdown.",
		fromEmail: 'emily.nguyen@bigpond.com',
		fromName: 'Emily Nguyen',
		status: TicketStatus.OPEN,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-05-19T08:45:00Z'),
	},
	{
		subject: 'Will there be a course on Rust programming?',
		body: "I've been waiting for a Rust course on your platform. Is there one planned? It would be the main reason I'd upgrade to an annual plan.",
		fromEmail: 'pedro.alves.dev@sapo.pt',
		fromName: 'Pedro Alves',
		status: TicketStatus.OPEN,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-05-20T10:15:00Z'),
	},
	{
		subject: 'How do I access courses offline?',
		body: "I travel frequently and need to watch course videos without an internet connection. The download option doesn't seem to be available on my account.",
		fromEmail: 'kira.novak@gmail.com',
		fromName: 'Kira Novak',
		status: TicketStatus.OPEN,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-05-20T14:00:00Z'),
	},
	{
		subject: 'Looking for a course on system design interviews',
		body: "I have a senior engineer interview at a FAANG company in 8 weeks. Do you have a system design interview prep course? I couldn't find one.",
		fromEmail: 'ben.carter.swe@gmail.com',
		fromName: 'Ben Carter',
		status: TicketStatus.OPEN,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-05-21T09:30:00Z'),
	},
	{
		subject: 'Team plan pricing for 25 users',
		body: "We're evaluating learning platforms for our engineering team of 25. Can you provide pricing and details on the team/enterprise plan?",
		fromEmail: 'recruiting@techstartup.io',
		fromName: 'HR Team – TechStartup',
		status: TicketStatus.OPEN,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-05-21T11:00:00Z'),
	},
	{
		subject: 'Can I pause my subscription?',
		body: "I'm going on parental leave for 3 months and won't be able to study. Is there a way to pause my subscription rather than cancel it?",
		fromEmail: 'jessica.lee.dev@gmail.com',
		fromName: 'Jessica Lee',
		status: TicketStatus.OPEN,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-05-22T08:00:00Z'),
	},
	{
		subject: 'Request for closed captions in Spanish',
		body: "I'm a native Spanish speaker and my English is intermediate. Are there Spanish subtitles available for any of the courses?",
		fromEmail: 'valentina.reyes@gmail.com',
		fromName: 'Valentina Reyes',
		status: TicketStatus.OPEN,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-05-22T12:30:00Z'),
	},
	{
		subject: 'Is the AWS certification course up to date for 2026 exams?',
		body: "I'm preparing for the AWS Solutions Architect Associate exam this year. Is the course content aligned with the 2026 exam syllabus?",
		fromEmail: 'ravi.kumar.cloud@gmail.com',
		fromName: 'Ravi Kumar',
		status: TicketStatus.OPEN,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-05-23T09:00:00Z'),
	},
	{
		subject: 'How do I change my email address?',
		body: 'I changed jobs and my old work email is being deactivated. How do I update my account email to a personal address?',
		fromEmail: 'mark.hill.oldwork@company.com',
		fromName: 'Mark Hill',
		status: TicketStatus.OPEN,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-05-23T14:45:00Z'),
	},
	{
		subject: 'Suggestion: add a note-taking feature to lessons',
		body: "It would be really helpful to have an inline note-taking panel while watching lessons so I don't have to switch to a separate app. Has this been considered?",
		fromEmail: 'nadia.hassan@gmail.com',
		fromName: 'Nadia Hassan',
		status: TicketStatus.OPEN,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-05-24T10:00:00Z'),
	},
	{
		subject: 'Accessibility: keyboard navigation broken in course player',
		body: "I'm a screen reader user and the course video player is not keyboard-navigable. Play/pause and progress bar can't be controlled without a mouse.",
		fromEmail: 'thomas.wren.a11y@gmail.com',
		fromName: 'Thomas Wren',
		status: TicketStatus.OPEN,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-05-24T13:15:00Z'),
	},
	{
		subject: 'Do certificates expire or need renewal?',
		body: "I'm about to complete the DevOps Fundamentals course and want to include the certificate on my CV. Do your certificates expire?",
		fromEmail: 'paula.white.hr@gmail.com',
		fromName: 'Paula White',
		status: TicketStatus.OPEN,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-05-25T08:30:00Z'),
	},
	{
		subject: 'Bulk purchase of gift cards for employee incentives',
		body: "We'd like to buy 50 gift cards to give to employees as learning incentives. Do you offer bulk pricing on gift cards?",
		fromEmail: 'hr.manager@globalfirm.com',
		fromName: 'HR Manager – Global Firm',
		status: TicketStatus.OPEN,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-05-25T11:00:00Z'),
	},
	{
		subject: 'Feedback: instructor speaks too fast in the Docker course',
		body: "The Docker course instructor speaks very quickly and I find it hard to follow even at 0.75x speed. Any chance of a re-recording or additional pauses?",
		fromEmail: 'sam.green.learner@yahoo.com',
		fromName: 'Sam Green',
		status: TicketStatus.OPEN,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-05-26T09:45:00Z'),
	},

	// GENERAL – RESOLVED
	{
		subject: 'How do I get a receipt for tax purposes?',
		body: "I need a receipt for my annual subscription purchase for my tax return. I can't find a download option in my account.",
		fromEmail: 'alice.ford@icloud.com',
		fromName: 'Alice Ford',
		status: TicketStatus.RESOLVED,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-04-14T10:00:00Z'),
	},
	{
		subject: 'Can I transfer my subscription to another email?',
		body: "I created my account with a work email and my contract is ending. Can the subscription be transferred to my personal email?",
		fromEmail: 'ryan.baker@workmail.com',
		fromName: 'Ryan Baker',
		status: TicketStatus.RESOLVED,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-04-15T12:00:00Z'),
	},
	{
		subject: 'Are there live Q&A sessions with instructors?',
		body: 'Do any of the courses include live sessions or office hours where students can ask the instructor questions directly?',
		fromEmail: 'claire.rousseau@gmail.com',
		fromName: 'Claire Rousseau',
		status: TicketStatus.RESOLVED,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-04-16T09:00:00Z'),
	},
	{
		subject: 'Feedback: missing exercises in the Git course',
		body: 'The Git course has no hands-on exercises. I learn best by doing. Would you consider adding a practice sandbox?',
		fromEmail: 'leo.hoffman@gmail.com',
		fromName: 'Leo Hoffman',
		status: TicketStatus.RESOLVED,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-04-17T11:30:00Z'),
	},
	{
		subject: 'Unable to update billing country – page reloads without saving',
		body: "When I try to change my billing country in account settings the page just reloads and nothing saves.",
		fromEmail: 'nina.eriksson@gmail.com',
		fromName: 'Nina Eriksson',
		status: TicketStatus.RESOLVED,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-04-18T14:00:00Z'),
	},

	// GENERAL – CLOSED
	{
		subject: 'What is the recommended IDE for the Python course?',
		body: "The Python course intro mentions different IDE options but doesn't give a recommendation. Which IDE does the instructor use?",
		fromEmail: 'jack.davies@gmail.com',
		fromName: 'Jack Davies',
		status: TicketStatus.CLOSED,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-03-25T09:00:00Z'),
	},
	{
		subject: 'How long do I have access after subscribing?',
		body: "I just purchased a monthly plan. Does access expire at the end of the month or after exactly 30 days?",
		fromEmail: 'helen.young@gmail.com',
		fromName: 'Helen Young',
		status: TicketStatus.CLOSED,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-03-26T10:30:00Z'),
	},
	{
		subject: 'Does the iOS app support Picture-in-Picture?',
		body: "I like to watch videos in Picture-in-Picture mode while taking notes. Does your iOS app support this?",
		fromEmail: 'connor.james@gmail.com',
		fromName: 'Connor James',
		status: TicketStatus.CLOSED,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-03-27T08:15:00Z'),
	},
	{
		subject: 'Request to add Mandarin subtitles',
		body: "Many of my colleagues are Mandarin speakers. Adding Mandarin subtitles would greatly increase adoption of the platform in our company.",
		fromEmail: 'zhang.wei.corp@gmail.com',
		fromName: 'Zhang Wei',
		status: TicketStatus.CLOSED,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-03-28T13:00:00Z'),
	},

	// UNCATEGORISED – OPEN (recently received, not yet categorised)
	{
		subject: 'Problem with my account',
		body: "I'm having an issue with my account and need help urgently. Please contact me.",
		fromEmail: 'user1@example.com',
		fromName: 'User One',
		status: TicketStatus.OPEN,
		category: TicketCategory.UNCATEGORISED,
		createdAt: new Date('2026-05-28T08:00:00Z'),
	},
	{
		subject: 'Something went wrong during checkout',
		body: "I tried to buy a course and got an error message halfway through checkout. Not sure if I was charged.",
		fromEmail: 'user2@example.com',
		fromName: 'User Two',
		status: TicketStatus.OPEN,
		category: TicketCategory.UNCATEGORISED,
		createdAt: new Date('2026-05-28T09:00:00Z'),
	},
	{
		subject: "Course isn't loading for me",
		body: 'None of the videos are loading since this morning. Everything else online works fine.',
		fromEmail: 'user3@example.com',
		fromName: 'User Three',
		status: TicketStatus.OPEN,
		category: TicketCategory.UNCATEGORISED,
		createdAt: new Date('2026-05-28T10:00:00Z'),
	},
	{
		subject: 'I want my money back',
		body: "I'm not happy with the service and want a refund. Please process it ASAP.",
		fromEmail: 'user4@example.com',
		fromName: 'User Four',
		status: TicketStatus.OPEN,
		category: TicketCategory.UNCATEGORISED,
		createdAt: new Date('2026-05-28T11:00:00Z'),
	},
	{
		subject: 'Login not working',
		body: "I cannot log into my account. Password reset didn't help either.",
		fromEmail: 'user5@example.com',
		fromName: 'User Five',
		status: TicketStatus.OPEN,
		category: TicketCategory.UNCATEGORISED,
		createdAt: new Date('2026-05-28T12:00:00Z'),
	},
	{
		subject: 'Missing module in course',
		body: "The course page shows 12 modules but I can only see 10. Am I missing something?",
		fromEmail: 'user6@example.com',
		fromName: 'User Six',
		status: TicketStatus.OPEN,
		category: TicketCategory.UNCATEGORISED,
		createdAt: new Date('2026-05-29T08:00:00Z'),
	},
	{
		subject: 'Billing question',
		body: 'I have a question about my billing. Please get back to me.',
		fromEmail: 'user7@example.com',
		fromName: 'User Seven',
		status: TicketStatus.OPEN,
		category: TicketCategory.UNCATEGORISED,
		createdAt: new Date('2026-05-29T09:00:00Z'),
	},
	{
		subject: 'App keeps logging me out',
		body: "I get logged out after about 5 minutes of inactivity. This is very annoying. Is there a setting to extend the session?",
		fromEmail: 'user8@example.com',
		fromName: 'User Eight',
		status: TicketStatus.OPEN,
		category: TicketCategory.UNCATEGORISED,
		createdAt: new Date('2026-05-29T10:00:00Z'),
	},
	{
		subject: 'Wrong name on certificate',
		body: "My completion certificate has a typo in my name. It says 'Jon' instead of 'John'. Can you fix this?",
		fromEmail: 'user9@example.com',
		fromName: 'User Nine',
		status: TicketStatus.OPEN,
		category: TicketCategory.UNCATEGORISED,
		createdAt: new Date('2026-05-29T11:00:00Z'),
	},
	{
		subject: 'Payment failed but was charged',
		body: 'My payment showed as failed during checkout but I can see a charge on my bank statement.',
		fromEmail: 'user10@example.com',
		fromName: 'User Ten',
		status: TicketStatus.OPEN,
		category: TicketCategory.UNCATEGORISED,
		createdAt: new Date('2026-05-29T12:00:00Z'),
	},

	// More TECHNICAL tickets to reach 100 total
	{
		subject: 'Vite course: hot reload not working in the lab environment',
		body: "In the Vite + React course, the in-browser lab environment doesn't hot-reload when I save a file. I have to manually refresh every time.",
		fromEmail: 'lucas.martin@gmail.com',
		fromName: 'Lucas Martin',
		status: TicketStatus.OPEN,
		category: TicketCategory.TECHNICAL,
		createdAt: new Date('2026-05-26T10:00:00Z'),
	},
	{
		subject: 'TypeScript course: tsc compile step missing from lesson 3',
		body: 'Lesson 3 of the TypeScript course tells me to run tsc but there is no tsconfig.json in the starter files.',
		fromEmail: 'sophie.taylor@gmail.com',
		fromName: 'Sophie Taylor',
		status: TicketStatus.OPEN,
		category: TicketCategory.TECHNICAL,
		createdAt: new Date('2026-05-26T11:00:00Z'),
	},
	{
		subject: 'GitHub integration not connecting to my repository',
		body: "I'm trying to connect my GitHub account for the project submission feature but it keeps failing with 'access denied'.",
		fromEmail: 'haruto.yamamoto@gmail.com',
		fromName: 'Haruto Yamamoto',
		status: TicketStatus.OPEN,
		category: TicketCategory.TECHNICAL,
		createdAt: new Date('2026-05-27T08:00:00Z'),
	},
	{
		subject: 'Course completion percentage stuck at 98%',
		body: "I've watched every video and passed every quiz but the course still shows 98% complete. There's nothing left for me to do.",
		fromEmail: 'zoe.clark@icloud.com',
		fromName: 'Zoe Clark',
		status: TicketStatus.OPEN,
		category: TicketCategory.TECHNICAL,
		createdAt: new Date('2026-05-27T09:30:00Z'),
	},
	{
		subject: 'Live chat support widget not loading',
		body: 'The live chat button in the bottom right of the screen never loads. I just see a spinner forever.',
		fromEmail: 'eric.dupont@gmail.com',
		fromName: 'Éric Dupont',
		status: TicketStatus.OPEN,
		category: TicketCategory.TECHNICAL,
		createdAt: new Date('2026-05-27T11:00:00Z'),
	},
	{
		subject: 'Email notifications not arriving for new replies',
		body: "I have email notifications turned on for course discussion replies but I never receive them. My email is definitely correct.",
		fromEmail: 'grace.lin@gmail.com',
		fromName: 'Grace Lin',
		status: TicketStatus.RESOLVED,
		category: TicketCategory.TECHNICAL,
		createdAt: new Date('2026-04-20T10:00:00Z'),
	},
	{
		subject: 'Coupon code not applying at checkout',
		body: "I have a valid coupon code from a newsletter but entering it at checkout says 'invalid code'. I copied it directly from the email.",
		fromEmail: 'mike.jones@gmail.com',
		fromName: 'Mike Jones',
		status: TicketStatus.RESOLVED,
		category: TicketCategory.TECHNICAL,
		createdAt: new Date('2026-04-21T13:00:00Z'),
	},
	{
		subject: 'Watched lessons marked as unwatched after app update',
		body: 'After the app updated itself last night, around 40 lessons I had already watched are now shown as unwatched.',
		fromEmail: 'anna.bell@gmail.com',
		fromName: 'Anna Bell',
		status: TicketStatus.RESOLVED,
		category: TicketCategory.TECHNICAL,
		createdAt: new Date('2026-04-22T08:30:00Z'),
	},
	{
		subject: "Can't change playback speed above 1.5x on Safari",
		body: 'The playback speed selector maxes out at 1.5x on Safari 17. On Chrome I can go up to 2x.',
		fromEmail: 'dan.white@mac.com',
		fromName: 'Dan White',
		status: TicketStatus.CLOSED,
		category: TicketCategory.TECHNICAL,
		createdAt: new Date('2026-03-15T09:00:00Z'),
	},
	{
		subject: 'Embedded code snippets not rendering in lesson notes',
		body: 'Code blocks in the lesson notes section show raw markdown backtick syntax instead of formatted code.',
		fromEmail: 'olivia.scott@gmail.com',
		fromName: 'Olivia Scott',
		status: TicketStatus.CLOSED,
		category: TicketCategory.TECHNICAL,
		createdAt: new Date('2026-03-16T14:00:00Z'),
	},

	// More REFUND tickets
	{
		subject: 'Refund for duplicate purchase after payment error',
		body: "The payment page crashed and I clicked submit again. I can see two identical charges on my card for the same course.",
		fromEmail: 'victor.hugo.dev@gmail.com',
		fromName: 'Victor Hugo',
		status: TicketStatus.OPEN,
		category: TicketCategory.REFUND,
		createdAt: new Date('2026-05-26T14:00:00Z'),
	},
	{
		subject: "Refund request – course quality doesn't meet expectations",
		body: "The instructor reads directly from slides with no code demos. I've watched the first 4 modules and it's not the hands-on experience advertised.",
		fromEmail: 'natalie.brown@gmail.com',
		fromName: 'Natalie Brown',
		status: TicketStatus.OPEN,
		category: TicketCategory.REFUND,
		createdAt: new Date('2026-05-27T10:00:00Z'),
	},
	{
		subject: 'VAT charged incorrectly – I am in a tax-exempt region',
		body: "VAT was applied to my purchase but I'm in a region where digital educational services are VAT-exempt. I'd like the VAT amount refunded.",
		fromEmail: 'jan.kovar@seznam.cz',
		fromName: 'Jan Kovář',
		status: TicketStatus.OPEN,
		category: TicketCategory.REFUND,
		createdAt: new Date('2026-05-28T08:30:00Z'),
	},
	{
		subject: 'Refund for unused seats after team downsizing',
		body: "We had to reduce our engineering team and now have 4 unused seats on our team plan with 8 months remaining. Can we get a partial refund?",
		fromEmail: 'cto@midsize-startup.com',
		fromName: 'CTO – Mid-size Startup',
		status: TicketStatus.RESOLVED,
		category: TicketCategory.REFUND,
		createdAt: new Date('2026-04-25T11:00:00Z'),
	},
	{
		subject: 'Charged in USD instead of AUD',
		body: "My account is set to Australian dollars but I was charged in USD. The exchange rate means I paid significantly more than the advertised price.",
		fromEmail: 'lachlan.r@gmail.com',
		fromName: 'Lachlan Reynolds',
		status: TicketStatus.RESOLVED,
		category: TicketCategory.REFUND,
		createdAt: new Date('2026-04-26T09:30:00Z'),
	},

	// More GENERAL tickets
	{
		subject: 'How do I add a second language to my profile?',
		body: "I'm a polyglot and would like to list multiple spoken languages on my learner profile. Is this supported?",
		fromEmail: 'marie.dubois@gmail.com',
		fromName: 'Marie Dubois',
		status: TicketStatus.OPEN,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-05-26T15:00:00Z'),
	},
	{
		subject: 'Partnership inquiry: corporate training programme',
		body: "I represent a university and we're interested in licensing your content for a structured corporate training programme. Who should I speak to?",
		fromEmail: 'partnerships@uni-edu.org',
		fromName: 'Partnerships Team',
		status: TicketStatus.OPEN,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-05-27T14:00:00Z'),
	},
	{
		subject: 'Is there a community forum or Discord for students?',
		body: "I'd love to connect with other learners taking the same courses. Do you have a student community Discord or Slack workspace?",
		fromEmail: 'ben.nguyen.dev@gmail.com',
		fromName: 'Ben Nguyen',
		status: TicketStatus.OPEN,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-05-28T10:30:00Z'),
	},
	{
		subject: 'Request for dyslexia-friendly font option',
		body: "I have dyslexia and would find it much easier to read lesson notes if there was an option to switch to a dyslexia-friendly font like OpenDyslexic.",
		fromEmail: 'kate.robinson@gmail.com',
		fromName: 'Kate Robinson',
		status: TicketStatus.OPEN,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-05-28T13:00:00Z'),
	},
	{
		subject: 'How do I update my name on my account?',
		body: "I got married last month and changed my last name legally. How do I update my display name and have it reflected on my certificates?",
		fromEmail: 'jessica.carter@gmail.com',
		fromName: 'Jessica Carter',
		status: TicketStatus.RESOLVED,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-04-28T10:00:00Z'),
	},
	{
		subject: 'Do you have an affiliate programme?',
		body: "I run a tech blog and would like to recommend your courses to my readers. Do you have an affiliate or referral programme?",
		fromEmail: 'tech.blogger@substack.com',
		fromName: 'Tech Blogger',
		status: TicketStatus.RESOLVED,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-04-29T11:30:00Z'),
	},
	{
		subject: 'Request to add keyboard shortcut for next lesson',
		body: "It would save a lot of time if there were a keyboard shortcut (e.g. N or →) to advance to the next lesson without using the mouse.",
		fromEmail: 'power.user.dev@gmail.com',
		fromName: 'Power User',
		status: TicketStatus.CLOSED,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-03-30T10:00:00Z'),
	},
	{
		subject: 'SQL course: connection string for PostgreSQL lab not working',
		body: "The connection string provided in the SQL course lab setup gives 'connection refused'. I followed the instructions exactly.",
		fromEmail: 'adam.b.sql@gmail.com',
		fromName: 'Adam Baker',
		status: TicketStatus.OPEN,
		category: TicketCategory.TECHNICAL,
		createdAt: new Date('2026-05-29T13:00:00Z'),
	},
	{
		subject: 'Android app not available in my country',
		body: "The Google Play listing says this app is not available in my country (Pakistan). Can I sideload it or access courses another way?",
		fromEmail: 'ali.raza.pk@gmail.com',
		fromName: 'Ali Raza',
		status: TicketStatus.OPEN,
		category: TicketCategory.TECHNICAL,
		createdAt: new Date('2026-05-29T14:00:00Z'),
	},
	{
		subject: "Profile picture upload fails – 'unsupported format' error",
		body: 'Trying to upload a JPEG profile picture and getting an unsupported format error. The file is a standard JPEG under 2MB.',
		fromEmail: 'claire.p.art@gmail.com',
		fromName: 'Claire Petit',
		status: TicketStatus.RESOLVED,
		category: TicketCategory.TECHNICAL,
		createdAt: new Date('2026-04-23T10:00:00Z'),
	},
	{
		subject: 'Kubernetes course lab environments time out too quickly',
		body: 'The Kubernetes lab environment disconnects after 10 minutes of inactivity. Some exercises take longer than that to set up.',
		fromEmail: 'devops.learner@gmail.com',
		fromName: 'DevOps Learner',
		status: TicketStatus.OPEN,
		category: TicketCategory.TECHNICAL,
		createdAt: new Date('2026-05-30T09:00:00Z'),
	},
	{
		subject: 'Refund – course purchased during sale but sale price not applied',
		body: "I purchased during the Black Friday sale but was charged the full price. The discount code wasn't applied even though I used the sale link.",
		fromEmail: 'bargain.hunter@gmail.com',
		fromName: 'Bargain Hunter',
		status: TicketStatus.OPEN,
		category: TicketCategory.REFUND,
		createdAt: new Date('2026-05-30T10:00:00Z'),
	},
	{
		subject: "Can't delete my account – settings page doesn't save",
		body: "I want to delete my account but the 'Delete Account' button in settings brings up a confirmation dialog that never closes, and the account isn't deleted.",
		fromEmail: 'delete.me.please@gmail.com',
		fromName: 'Delete Request',
		status: TicketStatus.OPEN,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-05-30T11:00:00Z'),
	},
	{
		subject: 'Request for WCAG 2.1 compliance report',
		body: "Our company's procurement team requires a WCAG 2.1 accessibility compliance report before we can purchase team licences. Can you provide one?",
		fromEmail: 'it.procurement@enterprise.com',
		fromName: 'IT Procurement',
		status: TicketStatus.OPEN,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-05-30T12:00:00Z'),
	},
	{
		subject: 'Course not showing in my library after gifting',
		body: "A friend gifted me the Python course but it never appeared in my library. My friend has a purchase confirmation email.",
		fromEmail: 'gift.recipient@gmail.com',
		fromName: 'Gift Recipient',
		status: TicketStatus.OPEN,
		category: TicketCategory.TECHNICAL,
		createdAt: new Date('2026-05-31T08:00:00Z'),
	},
	{
		subject: 'Price displayed in wrong currency on checkout',
		body: "The course is listed in GBP on the course page but switches to EUR at checkout. I'm in the UK and should be charged in GBP.",
		fromEmail: 'uk.customer@gmail.com',
		fromName: 'UK Customer',
		status: TicketStatus.OPEN,
		category: TicketCategory.TECHNICAL,
		createdAt: new Date('2026-05-31T09:00:00Z'),
	},
	{
		subject: 'Refund – employer declined to reimburse, requesting cancellation',
		body: "I purchased the course expecting employer reimbursement, but my request was denied. I'm within the 14-day refund window and would like to cancel.",
		fromEmail: 'disappointed.learner@gmail.com',
		fromName: 'Disappointed Learner',
		status: TicketStatus.OPEN,
		category: TicketCategory.REFUND,
		createdAt: new Date('2026-05-31T10:00:00Z'),
	},
	{
		subject: 'Suggestion: add estimated completion time to course listing',
		body: "It would help to know the estimated total hours before starting a course so I can plan my study schedule. Can you add this to course listings?",
		fromEmail: 'busy.professional@gmail.com',
		fromName: 'Busy Professional',
		status: TicketStatus.OPEN,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-05-31T11:00:00Z'),
	},
	{
		subject: 'Video quality drops to 144p automatically',
		body: "Course videos drop to 144p quality after a few minutes even though I have a fast broadband connection. Auto quality should not be selecting such a low resolution.",
		fromEmail: 'hd.only@gmail.com',
		fromName: 'HD Only',
		status: TicketStatus.OPEN,
		category: TicketCategory.TECHNICAL,
		createdAt: new Date('2026-06-01T08:00:00Z'),
	},
	{
		subject: 'React course: useState example code has a bug in lesson 9',
		body: "The useState example in lesson 9 uses setCount(count + 1) inside a loop, which produces incorrect results. This should use the functional update form.",
		fromEmail: 'react.nitpick@gmail.com',
		fromName: 'React Nitpick',
		status: TicketStatus.OPEN,
		category: TicketCategory.TECHNICAL,
		createdAt: new Date('2026-06-01T09:00:00Z'),
	},
	{
		subject: 'Unsubscribe from marketing emails',
		body: "I've clicked the unsubscribe link in several emails but I'm still receiving promotional emails. Please remove me from your mailing list.",
		fromEmail: 'stop.email@gmail.com',
		fromName: 'Unsubscribe Request',
		status: TicketStatus.CLOSED,
		category: TicketCategory.GENERAL,
		createdAt: new Date('2026-03-31T09:00:00Z'),
	},
];

await prisma.ticket.createMany({ data: tickets });
console.log(`Seeded ${tickets.length} tickets.`);
await prisma.$disconnect();
